
- name: Deploy to VPS
  run: |
    ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
      ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
        set -e
        cd /var/www/saro &&
        git fetch origin main &&
        git reset --hard origin/main &&

        # Write production environment variables
        echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' > .env.production
        echo 'NODE_ENV=production' >> .env.production
        echo 'PORT=5000' >> .env.production
        echo 'SESSION_SECRET=${{ secrets.SESSION_SECRET }}' >> .env.production

        # Reinstall dependencies
        rm -rf node_modules
        npm ci

        # Build project
        npm run build

        # Run migrations
        npx drizzle-kit push

        # Restart PM2 with env
        pm2 delete saro || true
        pm2 start dist/index.js --name saro -f --env production
        pm2 save
    "
