name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
              set -e
              cd /var/www/saro || (mkdir -p /var/www/saro && cd /var/www/saro)

              # Pull latest code
              if [ -d .git ]; then
                git fetch origin main
                git reset --hard origin/main
              else
                git clone https://github.com/sahidx/saro.git .
              fi

              # Write .env.production
              cat > .env.production <<EOL
DATABASE_URL=${{ secrets.DATABASE_URL }}
NODE_ENV=production
PORT=5000
SESSION_SECRET=${{ secrets.SESSION_SECRET }}
EOL

              # Clean & install deps
              rm -rf node_modules package-lock.json
              npm install --legacy-peer-deps

              # Build both client + server
              npm run build:all

              # Run DB migrations (ignore failure)
              npm run db:push || echo '⚠️ Migration failed, continuing...'

              # Restart app
              pm2 delete saro || true
              pm2 start dist/index.js --name saro --update-env -f
              pm2 save
          "
